
-- CREATE DATABASE postgres;
-- GRANT ALL PRIVILEGES ON DATABASE postgres TO postgres;
-- CREATE SCHEMA public;
CREATE TABLE public.T_TEST
(
    id SERIAL NOT NULL,
    C_TEST VARCHAR(60) NOT NULL,
    PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);
