version: "3"
services:

  # zookeeper:
  #   image: wurstmeister/zookeeper
  #   ports:
  #     - "2181:2181"
  #   networks:
  #     - check-time
      
  # kafka:
  #   build: https://github.com/wurstmeister/kafka-docker.git
  #   ports:
  #     - "9092:9092"
  #   # environment:
  #   #   KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
  #   #   KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #   environment:
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
  #     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
  #     KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
  #     KAFKA_ADVERTISED_PORT: 9092
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_CREATE_TOPICS: "javainuse-topic:1:1"   # Topic명:Partition개수:Replica개수
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   networks:
  #     - check-time

  elasticsearch:
    image: elasticsearch:7.4.2
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - check-time

  db-fluentd:
    image: nanaones/fluentd:0.0.4
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
      - ./log:/logs
    links:
      - "elasticsearch"
    networks:
      - check-time

  DB-grafana:
    image: grafana/grafana:latest
    ports: 
      - "13000:3000"
    networks:
      - check-time

  DB-postgres:
    image: postgres:latest
    restart: always
    volumes:
      - ./query/:/docker-entrypoint-initdb.d/
    environment: 
      - LC_ALL=C.UTF-8
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=8015
      - POSTGRES_PORT=5432

    ports: 
      - "5432:5432" 
    networks:
      - check-time

  python-main:
    # image: nanaones/psycopg-test:0.0.6
    build:
      context: .
      dockerfile: ./psycopg-test/dockerfile
    volumes:
      - ./log:/logs
    depends_on:
      - DB-postgres

    environment:
      loop: 10
    networks:
      - check-time

networks:
  check-time: